[2024-09-12 22:04:48,625] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-12 22:04:51,925] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-8-1/mb16.json Launching profiler...
[2024-09-12 22:04:53,819] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 22:04:57,058] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 8, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 22:04:58,951] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 22:04:59,839] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 22:05:22,815] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 22:05:26,254] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 22:05:26,255] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-12 22:05:31,610] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-12 22:05:36,304] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 22:05:36,802] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 22:05:36,802] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 22:05:36,802] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 22:05:36,803] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 22:05:36,803] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 8 nodes latency
[2024-09-12 22:05:36,994] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 22:05:36,995] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 22:05:38,112] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223']
[2024-09-12 22:05:38,112] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 22:05:40,045] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 22:05:43,103] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 22:05:43,104] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 22:05:44,982] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 22:05:46,062] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 8)
min_nodes: 2, max_nodes: 8, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
[2024-09-12 22:05:46,987] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 22:05:46,988] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7]}
[2024-09-12 22:05:46,988] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 8, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7]}
[2024-09-12 22:05:46,989] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 36507
[2024-09-12 22:05:46,989] [INFO] [agent.py:232:forward_worker_port] Received worker port: 36507 from worker. Forwarding it to master...
[2024-09-12 22:05:46,992] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 22:05:46,992] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 36507 from master
[2024-09-12 22:05:47,238] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 22:05:47,238] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-12 22:05:47,238] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:47,634] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:47,862] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:48,178] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 22:05:48,414] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-12 22:05:48,500] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 4 x <oobleck.PipelineTemplate.2nodes> pipelines (b: 16)
B: 64
dataloader: mbs 16
[2024-09-12 22:06:04,032] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 22:06:04,032] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.026163578033447266, forward time: 10.382402420043945, backward time: 25.600691556930542
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 0 done
[2024-09-12 22:06:49,125] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 45092.43
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-12 22:06:49,127] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 9.5473 GB | cache_allocated: 11.3281 GB | max_cache_allocated: 11.3281 GB
step: 1
step in try: 1
load_mbs: 0.020437240600585938, forward time: 9.948904037475586, backward time: 25.625662326812744
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 1 done
[2024-09-12 22:07:27,399] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38272.29
[2024-09-12 22:07:27,400] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 2
step in try: 2
load_mbs: 0.02272176742553711, forward time: 9.942355632781982, backward time: 25.58055591583252
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 2 done
[2024-09-12 22:08:05,639] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38239.15
[2024-09-12 22:08:05,640] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 3
step in try: 3
load_mbs: 0.019450902938842773, forward time: 9.942765235900879, backward time: 25.586511611938477
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 3 done
[2024-09-12 22:08:43,906] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38266.15
[2024-09-12 22:08:43,907] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 4
step in try: 4
load_mbs: 0.021564006805419922, forward time: 9.941094636917114, backward time: 25.568669319152832
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 4 done
[2024-09-12 22:09:22,132] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38225.16
[2024-09-12 22:09:22,133] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 5
step in try: 5
load_mbs: 0.02061605453491211, forward time: 9.95236849784851, backward time: 25.585756301879883
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 5 done
[2024-09-12 22:10:00,329] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38196.28
[2024-09-12 22:10:00,330] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 6
step in try: 6
load_mbs: 0.02258896827697754, forward time: 9.944805383682251, backward time: 25.608776092529297
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 6 done
[2024-09-12 22:10:38,717] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38387.01
[2024-09-12 22:10:38,718] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 7
step in try: 7
load_mbs: 0.02197122573852539, forward time: 9.938387870788574, backward time: 25.584737300872803
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 7 done
[2024-09-12 22:11:17,027] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38309.13
[2024-09-12 22:11:17,028] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 8
step in try: 8
load_mbs: 0.02129840850830078, forward time: 9.943695545196533, backward time: 25.601317882537842
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 8 done
[2024-09-12 22:11:55,236] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38207.61
[2024-09-12 22:11:55,237] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 9
step in try: 9
load_mbs: 0.021416425704956055, forward time: 9.9456205368042, backward time: 25.59391713142395
load_mbs cnt: 16, forward cnt: 16, backward cnt: 16
training step: 9 done
[2024-09-12 22:12:33,535] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 38298.51
[2024-09-12 22:12:33,536] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
[2024-09-12 22:12:33,536] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-12 22:12:34,020] [INFO] [engine.py:935:train] Training done.
