[2024-09-13 02:29:32,504] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-13 02:29:35,645] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_2_7B-8-9-1/mb8.json Launching profiler...
[2024-09-13 02:29:37,567] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 02:29:40,793] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 9, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 02:29:42,944] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_2_7B
[2024-09-13 02:29:44,108] [INFO] [profiler.py:284:profile] model loaded
[2024-09-13 02:30:24,427] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-13 02:30:27,173] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-13 02:30:27,174] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-13 02:30:33,442] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-13 02:30:38,973] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-13 02:30:39,489] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-13 02:30:39,489] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-13 02:30:39,489] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-13 02:30:39,490] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-13 02:30:39,490] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 9 nodes latency
[2024-09-13 02:30:39,705] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-13 02:30:39,705] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-13 02:30:40,760] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220']
[2024-09-13 02:30:40,760] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-13 02:30:42,695] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 02:30:45,769] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-13 02:30:45,769] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 02:30:47,749] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2560, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 32}
model_name: gpt2, model_tag: gpt3_2_7B
mb size: 34, ar across: 34, ar in: 34
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-13 02:30:49,211] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (3, 9)
min_nodes: 3, max_nodes: 9, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:12] with 1 devices
StageExecutionResult[13:23] with 1 devices
StageExecutionResult[24:33] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:18] with 1 devices
StageExecutionResult[19:26] with 1 devices
StageExecutionResult[27:33] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:21] with 1 devices
StageExecutionResult[22:27] with 1 devices
StageExecutionResult[28:33] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:12] with 1 devices
StageExecutionResult[13:18] with 1 devices
StageExecutionResult[19:23] with 1 devices
StageExecutionResult[24:28] with 1 devices
StageExecutionResult[29:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:15] with 1 devices
StageExecutionResult[16:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[26:29] with 1 devices
StageExecutionResult[30:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:9] with 1 devices
StageExecutionResult[10:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:26] with 1 devices
StageExecutionResult[27:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:24] with 1 devices
StageExecutionResult[25:27] with 1 devices
StageExecutionResult[28:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
[2024-09-13 02:30:53,364] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-13 02:30:53,364] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-13 02:30:53,364] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 9, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-13 02:30:53,365] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 38217
[2024-09-13 02:30:53,365] [INFO] [agent.py:232:forward_worker_port] Received worker port: 38217 from worker. Forwarding it to master...
[2024-09-13 02:30:53,367] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-13 02:30:53,367] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 38217 from master
[2024-09-13 02:30:54,167] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-13 02:30:54,167] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-13 02:30:54,167] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
MindtPy initialization may have generated poor quality cuts.
[2024-09-13 02:30:54,300] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 02:30:54,534] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 02:30:54,775] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-13 02:30:54,857] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.9nodes> pipelines (b: 128)
B: 128
dataloader: mbs 8
[2024-09-13 02:31:03,244] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-13 02:31:03,244] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.07558703422546387, forward time: 16.2959201335907, backward time: 41.62658953666687
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 0 done
[2024-09-13 02:32:11,257] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 68001.30
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-13 02:32:11,259] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 6.3805 GB | cache_allocated: 7.2949 GB | max_cache_allocated: 7.2949 GB
step: 1
step in try: 1
load_mbs: 0.07209181785583496, forward time: 15.816420793533325, backward time: 41.56726789474487
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 1 done
[2024-09-13 02:33:13,304] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62040.45
[2024-09-13 02:33:13,305] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 2
step in try: 2
load_mbs: 0.07355213165283203, forward time: 15.817107915878296, backward time: 41.56605768203735
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 2 done
[2024-09-13 02:34:15,335] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62025.75
[2024-09-13 02:34:15,336] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 3
step in try: 3
load_mbs: 0.07597994804382324, forward time: 15.821354150772095, backward time: 41.569206953048706
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 3 done
[2024-09-13 02:35:17,363] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62022.64
[2024-09-13 02:35:17,363] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 4
step in try: 4
load_mbs: 0.0684041976928711, forward time: 15.815510272979736, backward time: 41.567970752716064
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 4 done
[2024-09-13 02:36:19,400] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62033.10
[2024-09-13 02:36:19,401] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 5
step in try: 5
load_mbs: 0.06669831275939941, forward time: 15.814738273620605, backward time: 41.57044696807861
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 5 done
[2024-09-13 02:37:21,466] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62061.32
[2024-09-13 02:37:21,467] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 6
step in try: 6
load_mbs: 0.0727686882019043, forward time: 15.818481922149658, backward time: 41.57449460029602
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 6 done
[2024-09-13 02:38:23,548] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62077.35
[2024-09-13 02:38:23,549] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 7
step in try: 7
load_mbs: 0.07153701782226562, forward time: 15.818199634552002, backward time: 41.57686424255371
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 7 done
[2024-09-13 02:39:25,611] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62059.09
[2024-09-13 02:39:25,612] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 8
step in try: 8
load_mbs: 0.07574248313903809, forward time: 15.817728996276855, backward time: 41.56561851501465
load_mbs cnt: 128, forward cnt: 128, backward cnt: 128
training step: 8 done
[2024-09-13 02:40:27,645] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 62047.45
[2024-09-13 02:40:27,646] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 3.3817 GB | max_mem_allocated: 8.0420 GB | cache_allocated: 9.3984 GB | max_cache_allocated: 9.3984 GB
step: 9
step in try: 9
