[2024-09-13 02:29:35,307] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 4
[2024-09-13 02:29:38,738] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_2_7B-8-9-1/mb8.json Launching profiler...
[2024-09-13 02:29:40,593] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 02:29:43,766] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 4, world_size 9, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 02:29:45,904] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_2_7B
[2024-09-13 02:29:47,114] [INFO] [profiler.py:284:profile] model loaded
[2024-09-13 02:30:26,727] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-13 02:30:27,180] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-13 02:30:27,180] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-13 02:30:39,497] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-13 02:30:39,498] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-13 02:30:39,498] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-13 02:30:39,500] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-13 02:30:39,501] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 9 nodes latency
[2024-09-13 02:30:39,713] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-13 02:30:39,713] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-13 02:30:40,934] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.46:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220']
[2024-09-13 02:30:40,935] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-13 02:30:42,953] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 02:30:46,155] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-13 02:30:46,155] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.46:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-13 02:30:48,047] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2560, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 32}
model_name: gpt2, model_tag: gpt3_2_7B
mb size: 34, ar across: 34, ar in: 34
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-13 02:30:49,555] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (3, 9)
min_nodes: 3, max_nodes: 9, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:12] with 1 devices
StageExecutionResult[13:23] with 1 devices
StageExecutionResult[24:33] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:18] with 1 devices
StageExecutionResult[19:26] with 1 devices
StageExecutionResult[27:33] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:14] with 1 devices
StageExecutionResult[15:21] with 1 devices
StageExecutionResult[22:27] with 1 devices
StageExecutionResult[28:33] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:12] with 1 devices
StageExecutionResult[13:18] with 1 devices
StageExecutionResult[19:23] with 1 devices
StageExecutionResult[24:28] with 1 devices
StageExecutionResult[29:33] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:10] with 1 devices
StageExecutionResult[11:15] with 1 devices
StageExecutionResult[16:20] with 1 devices
StageExecutionResult[21:25] with 1 devices
StageExecutionResult[26:29] with 1 devices
StageExecutionResult[30:33] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:9] with 1 devices
StageExecutionResult[10:14] with 1 devices
StageExecutionResult[15:18] with 1 devices
StageExecutionResult[19:22] with 1 devices
StageExecutionResult[23:26] with 1 devices
StageExecutionResult[27:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
[2024-09-13 02:30:53,378] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-13 02:30:53,378] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 38217 from master
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:24] with 1 devices
StageExecutionResult[25:27] with 1 devices
StageExecutionResult[28:30] with 1 devices
StageExecutionResult[31:33] with 1 devices
[2024-09-13 02:30:53,814] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-13 02:30:53,815] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-13 02:30:53,815] [INFO] [engine.py:739:initialize_distributed] init pg: rank 4, world_size: 9, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-13 02:30:53,815] [INFO] [engine.py:755:initialize_distributed] Waiting for a port information...
[2024-09-13 02:30:53,815] [INFO] [engine.py:758:initialize_distributed] Received torch master: 172.21.0.42:2220.38217
[2024-09-13 02:30:54,180] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-13 02:30:54,180] [INFO] [engine.py:775:initialize_distributed] [rank: 4] Distributed initialization is done.
[2024-09-13 02:30:54,180] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
MindtPy initialization may have generated poor quality cuts.
[2024-09-13 02:30:54,283] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 02:30:54,508] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-13 02:30:54,751] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-13 02:30:54,833] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.9nodes> pipelines (b: 128)
B: 128
dataloader: mbs 8
[2024-09-13 02:31:03,258] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-13 02:31:03,259] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0, forward time: 16.13403296470642, backward time: 41.20336627960205
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 0 done
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
step: 1
step in try: 1
load_mbs: 0, forward time: 15.720179557800293, backward time: 41.18967390060425
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 1 done
step: 2
step in try: 2
load_mbs: 0, forward time: 15.720759868621826, backward time: 41.20244550704956
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 2 done
step: 3
step in try: 3
load_mbs: 0, forward time: 15.718942165374756, backward time: 41.19071841239929
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 3 done
step: 4
step in try: 4
load_mbs: 0, forward time: 15.719928979873657, backward time: 41.19618511199951
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 4 done
step: 5
step in try: 5
load_mbs: 0, forward time: 15.719735860824585, backward time: 41.19553470611572
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 5 done
step: 6
step in try: 6
load_mbs: 0, forward time: 15.72080135345459, backward time: 41.202730655670166
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 6 done
step: 7
step in try: 7
load_mbs: 0, forward time: 15.704803466796875, backward time: 41.16075158119202
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 7 done
step: 8
step in try: 8
load_mbs: 0, forward time: 15.7202787399292, backward time: 41.20533013343811
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 8 done
step: 9
step in try: 9
load_mbs: 0, forward time: 15.720744609832764, backward time: 41.207300662994385
load_mbs cnt: 0, forward cnt: 128, backward cnt: 128
training step: 9 done
[2024-09-13 02:41:28,367] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
